version: '2.1'

services:
  vulnwebapp:
    image: vulnwebapp
    build: .
    restart: always 
    environment:
      FLAG: ${FLAG}
      FLAG2: ${FLAG2}
      FLAG3: ${FLAG3}
      FLAG2PASS: ${FLAG2PASS}
    ports:
      - 80:5000
